title = "Hugo SEO theme"
baseURL = "https://example.com"
languageCode = "en-gb"
theme = "gohugo-thirdhemisphere"
themesDir = "../.."
copyright = "This work is licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-sa/4.0/' target = '_blank'>Creative Commons Attribution-ShareAlike 4.0 International </a> License."
disqusShortname = "xxx"
enableRobotsTXT = true

[author]
    name = "Peter Prevos"
    image = "/images/peter_prevos_small.jpg"

[params]
    description = "SEO-optimised theme for Hugo static websites."
    googleAnalytics = "xxx"
    logo = "/images/logo.png"
    cc = "fa fa-creative-commons"
    facebook = true
    twitter = "pprevos"
    reddit = true
    linkedin = true

[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.main]]
    name = "Categories"
    url = "/categories"

[[menu.main]]
    name = "Contact"
    url = "/contact/"

[[menu.footer]]
  name = "About"
  url = "/about/"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/pprevos"
    pre = "fab fa-github"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/pprevos"
    pre = "fab fa-twitter"


